<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="1" total="1" passed="0">
  <reporter-output>
  </reporter-output>
  <suite name="Default suite" duration-ms="43334" started-at="2018-05-30T19:18:03Z" finished-at="2018-05-30T19:18:46Z">
    <groups>
    </groups>
    <test name="Default test" duration-ms="43334" started-at="2018-05-30T19:18:03Z" finished-at="2018-05-30T19:18:46Z">
      <class name="com.UserLogin.LoginLogout">
        <test-method status="PASS" signature="checkSuiteToRun()[pri:0, instance:com.UserLogin.LoginLogout@6e75aa0d]" name="checkSuiteToRun" is-config="true" duration-ms="202" started-at="2018-05-30T15:18:03Z" finished-at="2018-05-30T15:18:03Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkSuiteToRun -->
        <test-method status="PASS" signature="checkCaseToRun()[pri:0, instance:com.UserLogin.LoginLogout@6e75aa0d]" name="checkCaseToRun" is-config="true" duration-ms="9506" started-at="2018-05-30T15:18:03Z" finished-at="2018-05-30T15:18:13Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- checkCaseToRun -->
        <test-method status="FAIL" signature="TestName(java.lang.String, java.lang.String, java.lang.String, java.lang.String, java.lang.String)[pri:0, instance:com.UserLogin.LoginLogout@6e75aa0d]" name="TestName" duration-ms="31422" started-at="2018-05-30T15:18:13Z" data-provider="LoginLogoutData" finished-at="2018-05-30T15:18:44Z">
          <params>
            <param index="0">
              <value>
                <![CDATA[test@test.com]]>
              </value>
            </param>
            <param index="1">
              <value>
                <![CDATA[hello]]>
              </value>
            </param>
            <param index="2">
              <value>
                <![CDATA[test123]]>
              </value>
            </param>
            <param index="3">
              <value>
                <![CDATA[Email ID and Password did not match]]>
              </value>
            </param>
            <param index="4">
              <value>
                <![CDATA[]]>
              </value>
            </param>
          </params>
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[The following asserts failed:
	null]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: The following asserts failed:
	null
	at org.testng.asserts.SoftAssert.assertAll(SoftAssert.java:48)
	at com.UserLogin.LoginLogout.TestName(LoginLogout.java:165)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:85)
	at org.testng.internal.Invoker.invokeMethod(Invoker.java:639)
	at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:821)
	at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:1131)
	at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:124)
	at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:108)
	at org.testng.TestRunner.privateRun(TestRunner.java:773)
	at org.testng.TestRunner.run(TestRunner.java:623)
	at org.testng.SuiteRunner.runTest(SuiteRunner.java:357)
	at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:352)
	at org.testng.SuiteRunner.privateRun(SuiteRunner.java:310)
	at org.testng.SuiteRunner.run(SuiteRunner.java:259)
	at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
	at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:86)
	at org.testng.TestNG.runSuitesSequentially(TestNG.java:1185)
	at org.testng.TestNG.runSuitesLocally(TestNG.java:1110)
	at org.testng.TestNG.run(TestNG.java:1018)
	at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:132)
	at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:236)
	at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:81)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- TestName -->
        <test-method status="PASS" signature="reporterDataResults()[pri:0, instance:com.UserLogin.LoginLogout@6e75aa0d]" name="reporterDataResults" is-config="true" duration-ms="392" started-at="2018-05-30T15:18:44Z" finished-at="2018-05-30T15:18:44Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- reporterDataResults -->
        <test-method status="PASS" signature="closeBrowser()[pri:0, instance:com.UserLogin.LoginLogout@6e75aa0d]" name="closeBrowser" is-config="true" duration-ms="1998" started-at="2018-05-30T15:18:44Z" finished-at="2018-05-30T15:18:46Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- closeBrowser -->
      </class> <!-- com.UserLogin.LoginLogout -->
    </test> <!-- Default test -->
  </suite> <!-- Default suite -->
</testng-results>
